- name: install nginx
  hosts: web
  become: yes
  tasks: #install nginx
    - name: install nginx
      ansible.builtin.package:
       - name: nginx
         state: installed
    -name: start nginx
      ansible.builtin.service:
        - name: nginx
          state: started
          enable: yes