- name: vars
  hosts: local
  connection: local
  vars:
   call: Deepika
   place: Chennai
  tasks: #vars
  - name: vars
    ansible.builtin.debug:
      msg: "my name is {{ call }} and im from {{ place }}"
  - name: vars
    vars:
      call: Deepu
      place: "sullurpeta,Alimili"
    ansible.builtin.debug:
      msg: "my name is {{ call }} and im from {{ place }}"