- name: vars
  hosts: local
  connection: local
  vars:
   name: Deepika
   place: Chennai
  tasks: #vars
  - name: vars
    ansible.builtin.debug:
     msg: "my name is {{name}} and im from {{chennai}}"